### ISSUE TITLE
Possibilidade de incluir outras bibliotecas de C

### ISSUE THREAD

**Issue by fpg1503** [birl-language/birl-server#11]
Precisamos de alguma frase para mapear para `#include <header.h>` e `#include "header.h`.

**Comment by lcfpadilha** [comment]
Ainda não vamos permitir o uso do #include para mais segurança no servidor, por enquanto só estamos incluindo a stdio.h e a math.h :)

**Comment by fpg1503** [comment]
Entendo, só toma cuidado pois como não há uma checagem para ver se o código é BIRL eu consigo escrever um código inteiro em C e compilar. Eu vi que você subiu uns fixes de segurança mas o problema é mais embaixo.

Um exemplo é: vocês querem evitar que pessoas incluam outras libs e para isso tira os `includes`. Além disso vocês tiram as funções do sistema porém do jeito que vocês estão fazendo eu posso escrever:

```
#isystemnclude <limits.h>

int main() {
    printf("oopsie %d", UCHAR_MAX);
    return 0;
}
```

ou então:

```
int main() {
    spopenystem("echo \"OMG OMG OMG\"");
    return 0;
}
```

É necessário rever a maneira como são lidados esses casos.
